# Set nginx base image
FROM nginx:1.11.8

# File Author / Maintainer
MAINTAINER Alexander Sheremisnkiy

# Copy custom configuration file from the current directory
COPY nginx.conf /etc/nginx/nginx.conf
